<a href="https://colab.research.google.com/github/Alsabaparveen/html-portfolio/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [18]:
arr=np.array([1,2,3,4,5],np.int8)
print(arr.shape)

(5,)


In [17]:
arr1=np.array([[1,2,3],[2,3,4]])
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
a = np.array([1, 2, 3,4,5], ndmin = 3) #convert 1D array into multi array specifying by admin
print(a)

[[[1 2 3 4 5]]]


In [11]:
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [13]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [19]:
arr=np.array({1,2,3,4})  #Creating an object
arr

array({1, 2, 3, 4}, dtype=object)

In [20]:
zero=np.zeros(3)  #Creating Zeros array
zero

array([0., 0., 0.])

In [21]:
zero=np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
one=np.ones(2)
one


array([1., 1.])

In [26]:
one=np.ones((5,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
rng=np.arange(5,dtype=int)
rng

array([0, 1, 2, 3, 4])

In [28]:
rng=np.arange(2,20,5)
rng

array([ 2,  7, 12, 17])

In [31]:
lins=np.linspace(20,40,4,dtype=int)
lins

array([20, 26, 33, 40])

In [32]:
x = np.empty([3,2], dtype = int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [33]:
y=np.empty((2,2))
y

array([[20., 26.],
       [33., 40.]])

In [35]:
identity=np.identity(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Axes in Numpy


In [40]:
arr=np.array([[1,2,3],[5,6,5],[3,4,5]])
arr

array([[1, 2, 3],
       [5, 6, 5],
       [3, 4, 5]])

In [43]:
arrSum=arr.sum(axis=0);
arrSum

array([ 9, 12, 13])

In [44]:
arrSum=arr.sum(axis=1);
arrSum

array([ 6, 16, 12])

In [45]:
arr.T

array([[1, 5, 3],
       [2, 6, 4],
       [3, 5, 5]])

In [46]:
# Iterator in array
arr.flat

In [47]:
for i in arr.flat:
  print(i)

1
2
3
5
6
5
3
4
5


In [64]:
arr.argmin()

0

In [65]:
arr.argmax()

4

In [66]:
arr.argmax(axis=0)

array([1, 1, 1])

In [67]:
arr.argmin(axis=1)

array([0, 0, 0])

In [50]:
print(arr.ndim)

2


In [51]:
print(arr.nbytes)

72


In [54]:
a=print(arr[0,1])

2


In [60]:
a=np.array([1,2,3,56,5])
a

array([ 1,  2,  3, 56,  5])

In [61]:
a.argmax()

3

In [62]:
a.argmin()

0

In [63]:
a.argsort()

array([0, 1, 2, 4, 3])

In [68]:
np.count_nonzero(a)

5

In [69]:
np.random.rand(3)  #radnom number between 0 and 1

array([0.51616339, 0.91310828, 0.29310001])

In [70]:
np.random.random(4)  #radnom number between 0.0 and 1.0

array([0.29261745, 0.64893651, 0.67748937, 0.26753459])

In [82]:
np.random.randint(5)

1

In [84]:
np.random.randint(1,10,20)

array([5, 4, 8, 8, 4, 8, 6, 9, 7, 6, 7, 3, 6, 2, 8, 7, 2, 2, 9, 8])

In [85]:
np.random.normal(0,1)

-0.7711301228558858